- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: present


- name: Copy Nginx configuration
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf


- name: Copy Node.js Nginx configuration
  ansible.builtin.template:
    src: nodejs.conf
    dest: /etc/nginx/conf.d/nodejs.conf


- name: Disable SELinux enforcement (temporary)
  ansible.builtin.command: setenforce 0
  ignore_errors: yes

- name: Restart Nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: true