- name: Add user 'spec'
  ansible.builtin.user:
    name: spec
    shell: /bin/bash
    create_home: yes

- name: Install Node.js and Git
  ansible.builtin.yum:
    name:
      - nodejs
      - git
    state: present
#####################################################################
- name: Check if app directory exists and is not empty
  ansible.builtin.find:
    paths: /home/spec/app
    file_type: any
  register: app_dir_contents
  ignore_errors: yes

- name: Remove existing app directory if not empty
  ansible.builtin.file:
    path: /home/spec/app
    state: absent
  when: app_dir_contents.matched > 0

- name: Clone application repository
  ansible.builtin.git:
    repo: "https://github.com/OpsInfinity/app.git"
    dest: /home/spec/app
    update: yes
    version: master

- name: Run application setup script
  ansible.builtin.shell: cat package.sh | bash
  args:
    chdir: /home/spec/app
#####################################################################



- name: Set MongoDB environment variables
  ansible.builtin.lineinfile:
    path: /etc/systemd/system/{{ component }}.service
    line: "Environment='MONGO_ENDPOINT=mongodb+srv://prasad:123Prasad@cluster0.3zmmc.mongodb.net/login-app-db?retryWrites=true&w=majority'"
    create: yes


- name: Copy SystemnD File
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest:  /etc/systemd/system/{{ component }}.service

- name: Start {{ component }} Service
  ansible.builtin.systemd:
    name: "{{ component }}"
    state: restarted
    enabled: yes
    daemon-reload: yes