- name: Add user 'spec'
  ansible.builtin.user:
    name: spec
    shell: /bin/bash
    create_home: yes

- name: Install Node.js and Git
  ansible.builtin.yum:
    name:
      - nodejs
      - git
    state: present

- name: Clone application repository
  ansible.builtin.git:
    repo: "https://github.com/OpsInfinity/app.git"
    dest: /home/spec/app
    update: yes
    version: master

- name: Run application setup script
  ansible.builtin.shell: cat package.sh | bash
  args:
    chdir: /home/spec/app


- name: Set MongoDB environment variables
  ansible.builtin.lineinfile:
    path: /etc/systemd/system/spec.service
    line: "Environment='MONGO_ENDPOINT=mongodb+srv://prasad:123Prasad@cluster0.3zmmc.mongodb.net/login-app-db?retryWrites=true&w=majority'"
    create: yes

- name: Copy systemd service file
  ansible.builtin.copy:
    src: files/spec.service
    dest: /etc/systemd/system/spec.service

- name: Restart spec service
  ansible.builtin.systemd:
    name: spec
    state: restarted
    enabled: true