- name: Add user 'spec'
  ansible.builtin.user:
    name: spec
    shell: /bin/bash
    create_home: yes

- name: Install Node.js and Git
  ansible.builtin.yum:
    name:
      - nodejs
      - git
    state: present

- name: Ensure app directory is removed if it's not a Git repository
  ansible.builtin.file:
    path: /home/spec/app
    state: absent
  when: not ansible.builtin.stat.path is defined

- name: Ensure app directory exists
  ansible.builtin.file:
    path: /home/spec/app
    state: directory
    owner: spec
    group: spec
    mode: '0755'

- name: Install NodeJS dependencies
  ansible.builtin.shell: npm install express path body-parser mongoose bcryptjs jsonwebtoken child_process pug util
  args:
    chdir: /home/spec/app

- name: Set MongoDB environment variables
  ansible.builtin.lineinfile:
    path: /etc/systemd/system/spec.service
    line: "Environment='MONGO_ENDPOINT=mongodb+srv://prasad:123Prasad@cluster0.3zmmc.mongodb.net/login-app-db?retryWrites=true&w=majority'"
    create: yes

- name: Copy systemd service file
  ansible.builtin.copy:
    src: files/spec.service
    dest: /etc/systemd/system/spec.service

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart spec service
  ansible.builtin.systemd:
    name: spec
    state: restarted
    enabled: true